---
- name: Install Java 1.7
  apt: pkg=openjdk-7-jre update_cache=yes

- name: Install wget
  apt: pkg=wget update_cache=yes

- name: Install CLI utils
  apt: pkg={{item}} update_cache=yes state=present
  with_items:
  - unzip
  - vim
  - ack-grep
  - git-core
  - python-pycurl
  - python-apt

