---
- name: WWW dir exists
  file: path=/var/www state=directory

- name: Get kibana
  get_url: url=http://download.elasticsearch.org/kibana/kibana/kibana-latest.zip dest=/tmp/kibana.zip

- name: Extract kibana
  unarchive: copy=no src=/tmp/kibana.zip dest=/var/www

- name: Install nginx
  apt: pkg=nginx update_cache=yes state=present

- name: Nginx config
  template: src=nginx.conf.j2 dest=/etc/nginx/sites-available/default
  notify:
    - restart nginx

